---
  - hosts: all
    tasks:
    - name: Install common software requirements
      yum: pkg={{ item }} state=installed
      with_items:
      - epel-release
      - git
      - traceroute
      - ipmitool
      - syslinux
      - vsftpd 
      - iptables
      - vnc
      - tftp-server
      - dnsmasq
      - system-config-kickstart
    - name: Change Root Password
      user: name=root update_password=always password="$6$WQxE8dZZ8nTC2FuX$ilLNL30zkltlbRnZO7IQfQvQL/f162N19KINL2nNyZb591EDHAP9OOvjxQlZAU1./tZ0aUJU6c0yRXill2sm81"
# mv /etc/dnsmasq.conf  /etc/dnsmasq.conf.backup
# nano /etc/dnsmasq.conf
# cp -r /usr/share/syslinux/* /var/lib/tftpboot
# mkdir /var/lib/tftpboot/pxelinux.cfg
# touch /var/lib/tftpboot/pxelinux.cfg/default
# nano /var/lib/tftpboot/pxelinux.cfg/default
# mkdir /var/lib/tftpboot/centos7
# cp /mnt/images/pxeboot/vmlinuz  /var/lib/tftpboot/centos7
# cp /mnt/images/pxeboot/initrd.img  /var/lib/tftpboot/centos7
# cp -r /mnt/*  /var/ftp/pub/ 
# chmod -R 755 /var/ftp/pub
# systemctl start dnsmasq
# systemctl status dnsmasq
# systemctl start vsftpd
# systemctl status vsftpd
# systemctl enable dnsmasq
# systemctl enable vsftpd
# netstat -tulpn
# firewall-cmd --add-service=ftp --permanent          ## Port 21
# firewall-cmd --add-service=dns --permanent          ## Port 53
# firewall-cmd --add-service=dhcp --permanent         ## Port 67
# firewall-cmd --add-port=69/udp --permanent          ## Port for TFTP
# firewall-cmd --add-port=4011/udp --permanent  ## Port for ProxyDHCP
# firewall-cmd --reload  ## Apply rules
# yum install pykickstart
#  ksvalidator /var/ftp/pub/anaconda-ks.cfg
#  mkdir -p /var/www/html/centos/6/x64
#  mount /dev/cdrom /media
#  cp -r /media/* /var/www/html/centos/6/x64/ 

#
# ks=http://192.168.0.4/ol6-112-server-ks.cfg
# install
# url --url http://192.168.0.4/OL6/
# linux ks=http://192.168.0.1/ks.cfg ip=192.168.0.100 gw=192.168.254.254 dns=192.168.0.2
#
# --bondslaves=
# When this option is used, the network device specified in the --device= option will be created using slaves defined in the --bondslaves= option. For example:
# network --device=mynetwork --bondslaves=em1,em2
# The above command will create a bond device named mynetwork using the em1 and em2 interfaces as its slaves.
# --bondopts=
# A list of optional parameters for a bonded interface, which is specified using the --bondslaves= and --device= options. Options in this list must be separated by commas (",") or semicolons (";"). If an option itself contains a comma, use a semicolon to separate the options. For example:
# network --bondopts=mode=active-backup,balance-rr;primary=eth1
# Available optional parameters are listed in the Working with Kernel Modules chapter of the Fedora System Administrator's Guide, available at http://docs.fedoraproject.org/.
# --vlanid=
# Specifies virtual LAN (VLAN) ID number (802.1q tag) for the device created using the device specified in --device= as a parent. For example, network --device=em1 --vlanid=171 will create a virtual LAN device em1.171.
# --interfacename=
# Specify a custom interface name for a virtual LAN device. This option should be used when the default name generated by the --vlanid= option is not desirable. This option must be used along with --vlanid=. For example:
# network --device=em1 --vlanid=171 --interfacename=vlan171
# The above command will create a virtual LAN interface named vlan171 on the em1 device with an ID of 171.
# The interface name can be arbitrary (for example, my-vlan), but in specific cases, the following conventions must be followed:
# If the name contains a dot (.), it must take the form of NAME.ID. The NAME is arbitrary, but the ID must be the VLAN ID. For example: em1.171 or my-vlan.171.
# Names starting with vlan must take the form of vlanID - for example, vlan171.
